[general]
font-sans = "Inter 28pt"
font-mono = "Inter 28pt"

[bar]
scale = 0.8999999761581421
padding-ends = 1.75
module-gap = 0.25
button-variant = "basic"
button-bg-opacity = 0
button-icon-size = 0.8500000238418579

[[bar.layout]]
monitor = "*"
show = true
left = [
    "dashboard",
    "hyprland-workspaces",
]
center = ["clock"]
right = [
    "network",
    "microphone",
    "volume",
    "bluetooth",
    "idle-inhibit",
    "systray",
]

[styling.palette]
bg = "#00000080"
surface = "#000000e6"
elevated = "#14171bcc"
fg = "#ffffff"
fg-muted = "#576175"
primary = "#5fafff"
red = "#5fafff"
yellow = "#5fafff"
green = "#5fafff"
blue = "#5fafff"

[modules.bluetooth]
icon-color = "fg-default"
label-color = "fg-default"

[modules.clock]
icon-show = false
label-color = "fg-default"

[modules.dashboard]
icon-override = "cm-moon-solid-full"
icon-color = "#ffffff"
right-click = "hyprpicker -a --no-fancy"
scroll-up = "exec $HOME/bin/wallpaper-changer.sh 1"
scroll-down = "exec $HOME/bin/wallpaper-changer.sh $RANDOM; notify-send a"

[modules.hyprland-workspaces]
min-workspace-count = 3
display-mode = "none"
app-icons-show = true
workspace-padding = 0.75
icon-size = 0.800000011920929

[modules.idle-inhibit]
startup-duration = 0
icon-color = "fg-default"
label-color = "fg-default"

[modules.microphone]
icon-color = "fg-default"
label-color = "fg-default"

[modules.network]
wired-connected-icon = "tbf-affiliate-symbolic"
wired-acquiring-icon = "tb-affiliate-symbolic"
wired-disconnected-icon = "tb-affiliate-symbolic"
icon-color = "fg-default"
label-color = "fg-default"

[modules.volume]
icon-color = "fg-default"
label-color = "fg-default"

[osd]
border = false

[wallpaper]
engine-enabled = false
cycling-enabled = true
cycling-directory = "/home/wuki/Desktop/Wallpaper/day/"
cycling-interval-mins = 60
